### ISSUE TITLE
Question regarding a couple of changes done in 1.30

### ISSUE THREAD

**Issue by jubalh** [arighi/virtme-ng#181] opened 2024-10-16 11:59 UTC
Maybe an issue is easier to keep track of this :)

I started to ask [here](https://github.com/arighi/virtme-ng/commit/05f9481b4566f84a26c32be6e0dfb10c64442d5e#r147942324) about a couple of changes that were done in 1.30.

To me it looks like https://github.com/arighi/virtme-ng/commit/05f9481b4566f84a26c32be6e0dfb10c64442d5e had a couple of side effects where I'm unsure whether they were intended.

The bash completion and virtme-ng.conf aren't installed anymore. @tamird kindly discussed this on the above mentioned thread already. And it appears to me that now only a pip based workflow will be supported. For package maintainers in distributions this might not be optimal. @arighi mentioned he also likes to have the bash completion file installed.

Another thing was that in virtme-ng, if `argparse-manpage` wasn't available it was gracefully failing and not building/installing the man pages. The rest was okay though.

This was nice because we could build virtme-ng also for older distributions, or distributions that didn't have that dependency and just don't ship the manpage there but virtme-ng we could still provide.

If this is the route the project will take it is of course fine. I just thought maybe these things are not intended or maybe people were not aware of these consequences.

**Comment by tamird** [comment] 2024-10-16 12:47
Maybe I wasn't clear: there's nothing preventing a distribution from packaging bash completions and global config files just as before. What's changed is that the pip build script will no longer do that because python packaging is moving towards hermeticity.

**Comment by jubalh** [comment] 2024-10-16 13:21
> there's nothing preventing a distribution from packaging bash completions and global config files just as before

My point is that https://github.com/arighi/virtme-ng/commit/05f9481b4566f84a26c32be6e0dfb10c64442d5e wasn't an atomic commit in my opinion. It had side effects not described in the commit message. And I would like to bring this to awareness and get clarification from the project whether this is what they actually intend to do.

**Comment by matttbe** [comment] 2024-10-16 14:58
Hello, 

Is there an important need to install virtme-ng in a venv?

Before the mentioned commit, it was recommended to install the tool using pip and `--break-system-packages`, which clearly meant: install it like a system package would do. As a command line tool that would be used from different directories (kernel source dir), using external tools (make, compiler, qemu, etc.) installed on the system, I don't think there are a lot of interests for hermeticity here, especially if it means loosing useful features. That's just my point of view.

**Comment by tamird** [comment] 2024-10-16 15:08
My selfish interest was building using `uv` rather than `pip`. Newer tools like `uv`, `rye`, `poetry`, etc. don't always support legacy features like `--break-system-packages`. If folks know of a way to please both worlds, that would be fine by me.

**Comment by arighi** [comment] 2024-10-16 15:24
I've received bug reports also from distros for the missing bash completion file, so I'd suggest this plan: let's revert the commit for now and then we'll try to re-introduce the same changes in a more incremental way and see if we can still figure out a way to install the missing files.

I think it's good to make the build process more compliant with the new systems, but we also don't want to break previous expected behaviors.

I'll also ask around, maybe someone more expert than me about python packaging will chime in...

**Comment by tamird** [comment] 2024-10-16 15:31
Do you have links to the recipes those distros use for packaging?

**Comment by arighi** [comment] 2024-10-16 15:35
> Do you have links to the recipes those distros use for packaging?

This is the one for Arch:
https://gitlab.archlinux.org/archlinux/packaging/packages/virtme-ng

**Comment by tamird** [comment] 2024-10-16 15:36
Here's what [ChatGPT suggests](https://gist.github.com/tamird/710312c0c4476dd50dba821dc6265519):

**Summary:**

- **Include** the bash completion script in your source package (e.g., in a `completions/` directory).
- **Do not** use `setup.py` or `setup.cfg` to install files into global system directories.
- **Use** your distro's packaging tools to install the script into `/usr/share/bash-completion/completions/` during the package build process.

So we can try to restore the completions into a subdirectory, and then hand it off to distro packaging to do the right thing with respect to global files.

**Comment by arighi** [comment] 2024-10-16 15:41
I'm fine with anything as long as it doesn't break stuff. :)

**Comment by matttbe** [comment] 2024-10-16 15:55
Here is what is done on Debian side: [salsa.debian.org](https://salsa.debian.org/debian/virtme-ng/-/blob/debian/debian/rules?ref_type=heads). It looks like extra steps are done to setup the completion, but nothing for the config file.

I know that a few projects have a special parameter to generate the bash completion files: `<cmd> completion` or `--completion` (see the [discussion](https://lore.kernel.org/tools/20241009-pypi-completion-v1-1-94f50a157c56@collins.com/T/#u) for the same issue with b4) or `--install-completion` (as mentioned in the [Python doc](https://packaging.python.org/en/latest/guides/creating-command-line-tools/#installing-the-package-with-pipx)). 

This is maybe a way to go: an extra step when using pip or uv, and distro can include the extra files.

Still, there might be something available for config files, using libs like https://pypi.org/project/platformdirs/ I suppose.

**Comment by hramrach** [comment] 2024-10-16 17:42
> Here's what [ChatGPT suggests](https://gist.github.com/tamird/710312c0c4476dd50dba821dc6265519):
> 
> **Summary:**
> 
> * **Include** the bash completion script in your source package (e.g., in a `completions/` directory).
> * **Do not** use `setup.py` or `setup.cfg` to install files into global system directories.
> * **Use** your distro's packaging tools to install the script into `/usr/share/bash-completion/completions/` during the package build process.
> 
> So we can try to restore the completions into a subdirectory, and then hand it off to distro packaging to do the right thing with respect to global files.

That is, however, a step backwards. Before the installation scripts included in the upstream source would fully install the tool, now they do not, and every distribution (and every individual user using the source directly) has to discover that these files are included in the source but not installed because the package chose to use a broken installation system, and invent some way to install them manually.

**Comment by tamird** [comment] 2024-10-16 17:46
I think you're misinformed. Distributions already have to do "extra stuff" including maintaining patches. See https://salsa.debian.org/debian/virtme-ng/-/commit/891ba4da433b35ff989c53357be32d51255144d3.

#183 would remove the need for them to maintain a patch (because they can control where to put completions externally).

**Comment by hramrach** [comment] 2024-10-16 19:32
> I think you're misinformed. Distributions already have to do "extra stuff" including maintaining patches. See https://salsa.debian.org/debian/virtme-ng/-/commit/891ba4da433b35ff989c53357be32d51255144d3.

No, I think you are neglecting a lot of information, and call people who take it into account misinformed.

That's because the distribution has specific ideas where to put the file, and the build system does not provide an option to customize that.

However, for the general user the installation is good enough as it was but your change breaks it by not installing part of the package.

> #183 would remove the need for them to maintain a patch (because they can control where to put completions externally).

But it would require everyone to find out that some files that should be installed are not installed by the package native build system, and maintain a local hack to install them.

On the other hand, reverting your patch and merging the Debian patch would alleviate the need for any hacks whatsoever, and the installation would just work.

**Comment by hramrach** [comment] 2024-10-16 19:56
The change in Debian you point out as 'extra stuff' distributions have to do was merged in 
891ba4da Talk about misinformed.

**Comment by arighi** [comment] 2024-10-17 05:53
I still have to follow all the details on this, so I may say something silly, but what about wrapping the current build around another build system, let's say meson for example. I think we can have a `meson install` to install files arbitrarily in the system. In this way distro people will just have to use meson to build/install the package and that will provide also the accessory files (bash completion, config file, man page, etc.). And at the same time we can still have the proper "containerization" of the python build system. Do you think this would solve the problem?

**Comment by tamird** [comment] 2024-10-17 08:24
Yes, but that can also be a shell script? 

*un*Installation might not work correctly though, I'm not sure how package managers track files belonging to a package.

**Closed** 2024-10-17 14:16 UTC

**Comment by jubalh** [comment] 2024-10-17 14:32
Thanks for solving this @arighi. Do you plan to create a new release as well?

**Comment by arighi** [comment] 2024-10-17 15:03
@jubalh yes, probably tomorrow or over the weekend.
